services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ={TZ}
    volumes:
      - ${DUTRAETC_FOLDER}/syncthing/config:/config
      - ${DUTRAETC_FOLDER}/syncthing/data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  wsgidav:
    image: mar10/wsgidav:latest
    container_name: webdav-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${DUTRAETC_FOLDER}/wsgidav:/var/wsgidav-root
      - ${DUTRAETC_FOLDER}/wsgidav.yaml:/wsgidav.yaml
    command: wsgidav --config=/wsgidav.yaml
