services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    volumes:
      - type: bind
        target: /config
        source: ${OLD_HDD}/unmanic/config
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/jellyfin
        target: /library
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/unmanic/tmp
        target: /unmanic_tmp
        bind:
          create_host_path: false
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    ports:
      - 11011:11011
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/cleanuparr/
        target: /config
        bind:
          create_host_path: false
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TZ}
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/prowlarr/
        target: /config
        bind:
          create_host_path: false
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    depends_on:
      - prowlarr
    environment:
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/qbittorrent/config
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${DOWNLOAD_PATH}
        target: /data
        bind:
          create_host_path: false
    ports:
      - "8080:8080"
      - "62609:62609"
      - 6881:6881
      - 6881:6881/udp

  jellyfin:
    image: linuxserver/jellyfin:latest
    restart: unless-stopped
    container_name: jellyfin
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - type: bind
        source: ${OLD_HDD}/jellyfin
        target: /data
        bind:
          create_host_path: false
      - type: bind
        source: ${APPDATA_PATH}/jellyfin/config
        target: /config
        bind:
          create_host_path: false
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${APPDATA_PATH}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${APPDATA_PATH}/caddy/caddy_data:/data
      - ${APPDATA_PATH}/caddy/caddy_config:/config
    depends_on:
      - jellyfin

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - qbittorrent
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/sonarr
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/jellyfin/tv
        target: /tv
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/qbittorrent/tv
        target: /data/tv
        bind:
          create_host_path: false
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/radarr
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/jellyfin/movies
        target: /movies
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD}/qbittorrent/movies
        target: /data/movies
        bind:
          create_host_path: false
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    container_name: jellyseerr
    depends_on:
      - sonarr
      - radarr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/jellyseerr
        target: /app/config
        bind:
          create_host_path: false
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - sonarr
      - radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${APPDATA_PATH}/bazarr
        target: /config
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/jellyfin/tv
        target: /tv
        bind:
          create_host_path: false
      - type: bind
        source: ${OLD_HDD}/jellyfin/movies
        target: /movies
        bind:
          create_host_path: false
    ports:
      - 6767:6767
    restart: unless-stopped
